name: Build TapSimulator Dylib

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ldid
      run: brew install ldid

    - name: Clone Theos
      run: |
        export THEOS=/opt/theos
        sudo mkdir -p $THEOS
        sudo chown -R $USER:staff $THEOS
        git clone --recursive https://github.com/theos/theos.git $THEOS

    - name: Build dylib
      run: |
        export THEOS=/opt/theos
        export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        export PREFIX=$SDKROOT/usr/
        sudo mkdir -p $SDKROOT/usr
        sudo ln -sf $(xcrun -f clang) $SDKROOT/usr/clang
        sudo ln -sf $(xcrun -f clang++) $SDKROOT/usr/clang++
        sudo ln -sf $(xcrun -f lipo) $SDKROOT/usr/lipo
        make clean
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TapSimulator.dylib
        path: "**/*.dylib"
